config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  
  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
  
  resources :posts
  
  resources :users, only: [:index, :show , :destroy] do
    resources :posts
  end
  
  resources :posts, only: [:index, :show] do
    resources :likes, only: [:create, :destroy]
  end
  
  root to: 'toppages#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @posts = @user.posts
    else
      @posts = Post.all
    end
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new()
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(posts_params)
    
    if @post.save
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(posts_params)
      redirect_to :action => "index"
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to posts_url
  end
  
  private
  
  def posts_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<%= form_for(@post) do |f| %>
<div class="form-group">
<%= f.label :title, 'タイトル' %>
<%= f.text_field :title %>
</div>

<div class="form-group">
<%= f.label :body, '投稿内容' %>
<%= f.text_field :body %>
</div>

<%= f.hidden_field :user_id, value: current_user.id %>

<%= f.submit '編集' %>
<% end %>

app/views/posts/index.html.erb
<% if @user.present? %>
  <h1><%= @user.email %>さんの記事一覧</h1>
<% else %>
  <h1>全ユーザーの記事一覧</h1>
<% end %>

<% @posts.each do |post| %>
  <li>タイトル: <%= link_to post.title, post %></li>
<% end %>
<%= link_to '新規投稿', new_user_post_path(user_id: current_user.id) %>

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>
<div class="form-group">
<%= f.label :title, 'タイトル' %>
<%= f.text_field :title %>
</div>

<div class="form-group">
<%= f.label :body, '投稿内容' %>
<%= f.text_field :body %>
</div>

<%= f.hidden_field :user_id, value: current_user.id %>

<%= f.submit '投稿' %>
<% end %>

app/views/posts/show.html.erb
<h1>タイトル: <%= @post.title %></h1>
<h2>投稿者: <%= @post.user.email %>さん</h2>

<h3>本文</h3>
<p><%= @post.body %></p>

<h3>いいね件数: <%= @post.likes.count %></h3>

<% if current_user.already_liked?(@post) %>
  <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
<% else %>
  <%= form_for [@post, @like] do |f| %>
    <% if @like.errors.any? %>
      <% @like.errors.full_messages.each do |msg| %>
        <li style="color:red;"><%= msg %></li>
      <% end %>
    <% end %>
    <%= f.submit 'いいね！' %>
  <% end %>
<% end %>

<h2>この記事にいいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
<%= link_to '新規投稿', new_user_post_path(user_id: current_user.id) %>
<%= link_to '編集', edit_user_post_path(user_id: current_user.id) %>
<%= link_to '削除', @post, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %>